version: '3.8'

x-airflow-common: &airflow-common
  build: .
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'

    SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
    SNOWFLAKE_USER: ${SNOWFLAKE_USER}
    SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
    SNOWFLAKE_ROLE: ${SNOWFLAKE_ROLE}
    SNOWFLAKE_DATABASE: ${SNOWFLAKE_DATABASE}
    SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE}
    SNOWFLAKE_SCHEMA: ${SNOWFLAKE_SCHEMA}

  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./dbt:/opt/airflow/dbt
    - ./ingestion:/opt/airflow/ingestion
    - ./utils:/opt/airflow/utils
    - ./logs:/opt/airflow/logs
    - ./data:/opt/airflow/data

services:

  postgres:
    image: postgres:13
    container_name: airflow_postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init

    depends_on:
      postgres:
        condition: service_healthy

    entrypoint: /bin/bash

    command: >
      -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com || true
      "

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver

    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

    command: webserver

    ports:
      - "8080:8080"

    restart: unless-stopped

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler

    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

    command: scheduler

    restart: unless-stopped